
[[ terrain ]]

[[ terrain ]]
    pos = [0, 1, 0]
    rot = [0, 0, 0]
    scl = [1, 1, 1]
    type="TerrainNode"
    [[terrain.instanced_trees]]
        pos = [0, 0, 0]
        rot = [0, 0, 0]
        scl = [1, 1, 1]

[[ character ]]
    pos = [1, 7, 3]
    rot = [0, 0, 0]
    scl = [1, 1, 1]
    type="BaseNode"
    [[character.character_camera]]
        pos = [0, 2, 0]
        rot = [0, 0, 0]
        scl = [1, 1, 1]
        type="Camera"
        fov= 70

    [[character.character_render]]
        pos = [0, 0, 0]
        rot = [0, 0, 0]
        scl = [1, 1, 1]
        type="Render"
        mesh="character.obj"
