[[ root ]]

    [[ root.terrain ]]
        type="TerrainNode"
    [[ root.character ]]
        pos = "10. 45. 12.44"
        type="BaseNode"
        [[root.character.character_camera]]
            type="Camera"
            fov="fov"
        [[root.character.character_render_obj]]
            type="Render"
            mesh="character.obj"
            textures= " ? ? ?"
