
[[ mov]]
    type = "Movement"
    sensitivity = 0.005
    speed = 0.005
    pos = [0.0, 0.0, -1.0] 
    rot = [0.0, 0.0, 0.0]
    scl = [1.0, 1.0, 1.0]
    [[ mov.main_cam ]]
        type="Camera"
        active_camera = true
        fov= 70
    
    # [[ mov.light_]]
    #     type = "Light"
    #     pos = [0.0 ,0.0, 0.0]
    #     diffuse = [1.0 ,0.0, 0.0]
    #     intensity = 1.0
    #     directional = false
    #     active = true

# [[ obj1]]
#     type="Base"
#     pos = [-50.0, 0.0, 0.0]
#     rot = [0.0, 0.0, 0.0]
    
#     [[obj1.mesh]]
#         type = "Mesh"
#         normal = true
#         program= "phong_DN"
#         mesh="res/meshs/moon.obj"
#         material="res/materials/moon.mtl"
#         scl = [0.2, 0.2, 0.2]


[[ obj2]]
    type="Base"
    pos = [-40.0, 10.0, -20.0]
    rot = [0.0, 0.0, 0.0]
    
    [[obj2.mesh]]
        type = "Mesh"
        normal = true
        program= "phong_DNS"
        mesh="res/meshs/moon.obj"
        material="res/materials/earth.mtl"
        scl = [0.2, 0.2, 0.2]


[[ triangle1]]
    type = "__TriangleDebug"
    program= "triangle_test"
    pos = [0.0, 0.0, 1.0]
    rot = [0.0, 0.0, 0.0]
    scl = [1.0, 1.0, 1.0]


[[ light_]]
    type = "Light"
    pos = [1.0 ,1.0, 0.0]
    ambient = [0.0 ,0.0, 0.0]
    diffuse = [1.0 ,1.0, 0.95]
    intensity = 1.0
    directional = true


[[ spacesship]]
    type="Mesh"
    program= "phong_DNSM"
    normal = true
    mesh="res/meshs/FA59AMako.obj"
    material="res/materials/FA59AMako.mtl"
    scl = [0.01, 0.01, 0.01]


[[plane]]
    type="Mesh"
    normal = true
    program= "phong_DNS"
    mesh="res/meshs/plane.obj"
    material="res/materials/plane.mtl"
    scl = [1.0, 1.0, 1.0]
    pos = [2.0, 0.0, 2.0]


[[skybox]]
    type="Skybox"
    program="skybox"
    left="res/textures/skybox/bkg1_left.png"
    right="res/textures/skybox/bkg1_right.png"
    top="res/textures/skybox/bkg1_top.png"
    bottom="res/textures/skybox/bkg1_bot.png"
    front="res/textures/skybox/bkg1_front.png"
    back="res/textures/skybox/bkg1_back.png"