
[[ mov]]
    type = "Movement"
    sensitivity = 0.005
    speed = 0.005
    pos = [0.0, 0.0, -1.0] 
    rot = [0.0, 0.0, 0.0]
    scl = [1.0, 1.0, 1.0]
    [[ mov.main_cam ]]
        type="Camera"
        active_camera = true
        fov= 70
    
    [[ mov.light_]]
        type = "Light"
        pos = [0.0 ,0.0, 0.0]
        diffuse = [1.0 ,0.0, 0.0]
        intensity = 10.0
        directional = false
        active = false

[[ obj1]]
    type="Base"
    pos = [-50.0, 0.0, 0.0]
    rot = [0.0, 0.0, 0.0]
    
    [[obj1.mesh]]
        type = "Mesh"
        program= "mesh_test"
        mesh="res/meshs/moon.obj"
        material="res/materials/moon.mtl"
        scl = [0.2, 0.2, 0.2]


[[ obj2]]
    type="Base"
    pos = [0.0, 0.0, 0.0]
    rot = [0.0, 0.0, 0.0]
    
    [[obj2.mesh]]
        type="Mesh"
        program= "mesh_test"
        mesh="res/meshs/Stone.obj"
        material="res/materials/Stone.mtl"
        scl = [0.2, 0.2, 0.2]


[[ triangle1]]
    type = "__TriangleDebug"
    program= "triangle_test"
    pos = [0.0, 0.0, 1.0]
    rot = [0.0, 0.0, 0.0]
    scl = [1.0, 1.0, 1.0]


[[ light_]]
    type = "Light"
    pos = [1.0 ,1.0, 0.0]
    ambient = [0.0 ,0.0, 0.0]
    diffuse = [1.0 ,1.0, 0.95]
    intensity = 1.0
    directional = true