
[[ mov]]
    type = "Movement"
    sensitivity = 0.005
    speed = 0.005

    [[mov.main_cam ]]
        type="Camera"
        active_camera = true
        fov= 70
        pos = [0.0, 0.3, 0.8] 
    [[mov.poss]]
        type="Base"
        [[mov.poss.spacesship]]
            type="Mesh"
            program= "phong_DNSM"
            normal = true
            mesh="res/meshs/FA59AMako.obj"
            material="res/materials/FA59AMako.mtl"
            scl = [0.01, 0.01, 0.01]
            rot = [0.0, 3.1415, 0.0]

    [[ mov.light_]]
        type = "Light"
        pos = [0.0 ,0.0, 0.0]
        rot = [0.0, -0.2, 0.0]
        diffuse = [1.0 ,1.0, 1.0]
        intensity = 100.0
        directional = false
        active = true
        angle = 17.5
    
    [[ mov.light_2]]
        type = "Light"
        pos = [0.0 ,0.0, 0.0]
        rot = [0.0, 0.2, 0.0]
        diffuse = [1.0 ,1.0, 1.0]
        intensity = 100.0
        directional = false
        active = true
        angle = 17.5



[[p1]]
    type="Rotating"
    frequency = 0.01
    rot = [0.0, 0.0, 1.57]
    [[ p1.o1]]
        type="Rotating"
        pos = [0.0, 0.0, 700.0]
        rot = [0.0, 0.0, 0.0]
        frequency = 0.07
        [[p1.o1.earth_mesh]]
                type = "Mesh"
                normal = true
                program= "phong_DNS"
                mesh="res/meshs/moon.obj"
                material="res/materials/earth.mtl"
                scl = [0.4, 0.4, 0.4]
                rot = [0.0, 0.0, 1.57]
        [[ p1.o1.b]]
            type = "Base"
            pos = [0.0, 0.0, 100.0]
            [[ p1.o1.b.moon_mesh]]
                type = "Mesh"
                normal = true
                program= "phong_DN"
                mesh="res/meshs/moon.obj"
                material="res/materials/moon.mtl"
                scl = [0.2, 0.2, 0.2]
            [[ p1.o1.b.o2]]
                type="Rotating"
                pos = [0.0, 0.0, 0.0]
                rot = [0.0, 0.0, 0.0]
                frequency = 0.2

            [[ p1.o1.b.o2.moon_mesh]]
                type = "Mesh"
                normal = true
                program= "phong_DN"
                mesh="res/meshs/moon.obj"
                material="res/materials/moon.mtl"
                scl = [0.1, 0.1, 0.1]
                pos = [0.0, 0.0, 35.0]

[[p2]]
    type="Rotating"
    frequency = 0.1
    rot = [0.0, 0.0, 1.57]
    [[p2.corr_par]]
        type="Base"
        pos = [0.0, 0.0, -400.0]

        [[p2.corr_par.pr]]
            type="Rotating"
            frequency = -0.14
            rot = [0.0, 0.0, 0.0]
            [[p2.corr_par.pr.corruscant_mesh]]
                        type = "Mesh"
                        normal = true
                        program= "phong_DNS"
                        mesh="res/meshs/moon.obj"
                        material="res/materials/corruscant.mtl"
                        scl = [0.5, 0.5, 0.5]
                        pos = [0.0, 0.0, -0.0]


        [[p2.corr_par.as_rot]]
            type="Rotating"
            pos = [0.0, 0.0, 0.0]
            rot = [0.0, 0.0, 0.0]
            frequency = 0.04
            [[p2.corr_par.as_rot.asteroid_mesh]]
                type = "MeshInstanced"
                normal = true
                program= "phong_DN_instanced"
                mesh="res/meshs/Stone.obj"
                material="res/materials/Stone.mtl"
                generator="ring"
                count = 1000

                scl = [1.0, 1.0, 1.0]
                pos = [0.0, 0.0, 0.0]
                rot = [0.0, 1.57, 0.0]

[[sun]]
    type = "Base"
    pos = [0.0, 0.0, 0.0]

    [[sun.light_]]
        type = "Light"
        pos = [0.0 ,0.0, 0.0]
        ambient = [0.07 ,0.07, 0.1]
        diffuse = [1.0 ,1.0, 0.95]
        intensity = 500000.0
        angle = 0.0
    [[sun.obj_mesh]]
                    type = "Mesh"
                    normal = true
                    program= "phong_DNS"
                    mesh="res/meshs/moon.obj"
                    material="res/materials/corruscant.mtl"
                    scl = [0.5, 0.5, 0.5]
                    pos = [0.0, 0.0, -0.0]


[[skybox]]
    type="Skybox"
    program="skybox"
    left="res/textures/skybox/bkg1_left.png"
    right="res/textures/skybox/bkg1_right.png"
    top="res/textures/skybox/bkg1_top.png"
    bottom="res/textures/skybox/bkg1_bot.png"
    front="res/textures/skybox/bkg1_front.png"
    back="res/textures/skybox/bkg1_back.png"
