
[[ mov]]
    type = "Movement"
    sensitivity = 0.005
    speed = 0.005
    pos = [0.0, 0.0, -1.0] 
    rot = [0.0, 0.0, 0.0]
    scl = [1.0, 1.0, 1.0]
    [[ mov.main_cam ]]
        type="Camera"
        active_camera = true
        fov= 70

[[ obj1]]
    type = "Mesh"
    program= "mesh_test"
    mesh="res/meshs/Stone.obj"
    material="res/materials/Stone.mtl"
    pos = [0.0, 0.0, 0.0]
    rot = [0.0, 0.0, 0.0]
    scl = [0.2, 0.2, 0.2]


[[ triangle1]]
    type = "__TriangleDebug"
    program= "triangle_test"
    pos = [0.0, 0.0, 1.0]
    rot = [0.0, 0.0, 0.0]
    scl = [1.0, 1.0, 1.0]