
[[ terrain ]]
    type="Camera"
    [[terrain.instanced_trees]]
        count = 1000

[[ character ]]
    type="Base"
    [[character.character_camera]]

        type="Camera"
        fov= 70

    [[character.character_render]]
        type="Camera"
        mesh="character.obj"
        [[character.character_render.random]]
            type = "Camera"
            property = 125
