[[skybox]]

vert = "res/shaders/skybox.vert"
frag = "res/shaders/skybox.frag"

# for .vert
VIEW_MATRIX_LOCATION = 1
#MODEL_MATRIX_LOCATION = 0
PROJECTION_MATRIX_LOCATION = 2

#for .frag
#MATERIAL_AMBIENT_COLOR_LOCATION = 8
#MATERIAL_DIFFUSE_COLOR_LOCATION = 9
#MATERIAL_SPECULAR_COLOR_LOCATION = 10
#MATERIAL_SHININESS_LOCATION = 11

#LIGHTS_BINDING = 0
#INSTANCED_BINDING = 1


CUBEMAP_BINDING = 0

#DIFFUSE_TEXTURE_BINDING = 0
#NORMAL_TEXTURE_BINDING = 1
#SPECULAR_TEXTURE_BINDING = 2
#METALIC_TEXTURE_BINDING = 3
EYE_POS_LOCATION = 0
#TIME_LOCATION = 12

