[[triangle_test]]

vert = "res/shaders/triangle_test.vert"
frag = "res/shaders/triangle_test.frag"

# for .vert
VIEW_MATRIX_LOCATION = 1
MODEL_MATRIX_LOCATION = 0
PROJECTION_MATRIX_LOCATION = 2

#for .frag
#MATERIAL_AMBIENT_COLOR_LOCATION = 3
#MATERIAL_DIFFUSE_COLOR_LOCATION = 4
#MATERIAL_SPECULAR_COLOR_LOCATION = 5
#MATERIAL_SHININESS_LOCATION = 6

#LIGHTS_BINDING = 0
#INSTANCED_BINDING = 1

#DIFFUSE_TEXTURE_BINDING = 0
#NORMAL_TEXTURE_BINDING = 1
#SPECULAR_TEXTURE_BINDING = 2

TIME_LOCATION = 3
